version: '2'
services:
  elastic-37:
    container_name: elasticsearch-grch-37
    image: dice-registry.ad.garvan.unsw.edu.au:5000/docker-bouncy_elastic-37
  elastic-38:
    container_name: elasticsearch-grch-38
    image: dice-registry.ad.garvan.unsw.edu.au:5000/docker-bouncy_elastic-38
  apache-37:
    container_name: apache-grch-37
    image: dice-registry.ad.garvan.unsw.edu.au:5000/docker-bouncy_apache-37
    ports:
      - "443:443"
  apache-38:
    container_name: apache-grch-38
    image: dice-registry.ad.garvan.unsw.edu.au:5000/docker-bouncy_apache-38
    ports:
      - "9500:443"
