version: '2'
services:
  elastic:
    container_name: elasticsearch-ensembl-grch37
    image: dice-registry.ad.garvan.unsw.edu.au:5000/elasticsearch-ensembl-grch37
  apache:
    container_name: httpd-reverse-proxy-to-elasticsearch
    image: dice-registry.ad.garvan.unsw.edu.au:5000/httpd-reverse-proxy-to-elasticsearch
    ports:
      - "443:80"
